version: '3.8'

services:
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - cluster-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HEALTH_CHECK_INTERVAL=30000
      - NODE_TIMEOUT=60000

  node-simulator:
    build: ./node-simulator
    environment:
      - API_SERVER_URL=http://api-server:5000
      - HEARTBEAT_INTERVAL=10000
      - NODE_ID=${HOSTNAME}
    networks:
      - cluster-network
    deploy:
      replicas: 0  # We'll scale this dynamically when adding nodes

networks:
  cluster-network:
    driver: bridge